version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      # 新たにrestore_cacheステップを追加
      - restore_cache:
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "setup.py" }}
            - v1-dependencies-{{ .Branch }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install .

      # 新たにsave_cacheステップを追加
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ .Branch }}-{{ checksum "setup.py" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest
      # 新たにstore_test_resultsステップを追加
      - store_test_results:
          path: test-reports
